#!/bin/bash

log()   { echo -e "\e[30;47m ${1^^} \e[0m ${@:2}"; }
info()  { echo -e "\e[48;5;28m ${1^^} \e[0m ${@:2}"; }
warn()  { echo -e "\e[48;5;202m ${1^^} \e[0m ${@:2}" >&2; }
error() { echo -e "\e[48;5;196m ${1^^} \e[0m ${@:2}" >&2; }

FILE=$(xdg-user-dir DOCUMENTS)/down.txt
DOWNLOAD=$(xdg-user-dir DOWNLOAD)

open() {
  xdg-open $FILE 2>/dev/null
  exit
}

elapsed() {
    local H=$(( $1 / 3600))
    local M=$((($1 % 3600) / 60))
    local S=$(( $1 % 60))
    [[ $1 -gt 3599 ]] \
        && info downloaded in $H hours $M minutes and $S seconds \
        || info downloaded in $M minutes and $S seconds;
}

# first execution
[[ ! -f $FILE ]] && { touch $FILE; open; }

# no urls found
[[ $(grep --count ^http $FILE) -eq 0 ]] && open;

# no ~/.netrc file
[[ ! -f ~/.netrc ]] && { error abort '~/.netrc file is required'; exit; }

# no machine in ~/.netrc file
MACHINE=$(base64 -d <<< MWZpY2hpZXIuY29tCg==)
[[ -z $(grep $MACHINE ~/.netrc) ]] \
  && { error abort "machine $MACHINE in ~/.netrc file is required"; exit; }

STARTED=$(date +'%s')

while true
do
  # exit if no more URL
  [[ $(grep --count ^http $FILE) -eq 0 ]] && break;
  # first available URL
  URL=$(grep ^http $FILE | head -n 1)
  # comment URL
  sed --expression "s|$URL|-$URL|" --in-place $FILE
  # get filename using --head
  NAME=$(curl "$URL" \
    --head \
    --netrc \
    --silent \
    --location \
    | grep ^Content-Disposition \
    | sed 's|.*filename="||' \
    | sed 's|";.*||')
  
  [[ -z $NAME ]] && { warn skip no filename for $URL; continue; }
  [[ -f "$DOWNLOAD/$NAME" ]] &&  { warn skip already downloaded $NAME; continue; }

  # download
  info download $URL
  log file $NAME
  curl "$URL" \
    --netrc \
    --location \
    --output "$DOWNLOAD/$NAME"
done

FINISHED=$(date +'%s')
elapsed $((FINISHED - STARTED))
exit 0